---
- name: Localhost provisioning
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  tasks:
  - name: Create an empty bucket
    amazon.aws.aws_s3:
      bucket: mybacket1.test5.com
      mode: create
      permission: public-read
  - name: ec2 group
    amazon.aws.ec2_group:
      name: EC2-sec
      description: WAR EC2 group
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0

  - name: Start instances
    ec2:
      instance_type: t2.micro
      key_name: my-key1
      image: ami-0dd9f0e7df0f0a138
      wait: yes
      wait_timeout: 900
      count: 2
      vpc_subnet_id: subnet-596e7223
      assign_public_ip: yes
      group: EC2-sec
      region: us-east-2
    register: output
  - name: add host to group 'just_created'
    add_host:
      name: "{{ output.instances[0].public_ip }}"
      groups: Buld
      name: "{{ output.instances[1].public_ip }}"
      groups: App

- name: Build provisioning
  hosts: Build
  become: yes
  tasks:
  - name: Ensure necessary packages is present
    apt:
      update_cache: yes
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - default-jdk
      - maven
      - git

  - name: Ensure the git repository is cloned
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/WAR
      clone: yes

  - name: Ensure war file is ready
    command: mvn package -f /tmp/WAR/pom.xml

#  - name: Ensure war file on local host
#    fetch:
#      src: /tmp/WAR/target/hello-1.0.war
#      dest: /tmp/

- name: Prod server provisioning
  hosts: App
  become: yes

  tasks:
    - name: Ensure tomcat is present
      apt:
        update_cache: yes
        name: tomcat9
        state: present

#    - name: Ensure war file on prod server
#      copy:
#        src: /tmp/dev1/tmp/WAR/target/hello-1.0.war
#        dest: /var/lib/tomcat9/webapps/hello-1.0.war